### ISSUE TITLE
Pyhton example running failed

### ISSUE THREAD

**Issue by jenamax** [lnstadrum/beatmup#24] opened 2022-10-26 09:03 UTC
Hello! I am trying to run Python example (cifar100) and get the following error when model training started. The version of Tensorflow is 2.7, Python - 3.9

===== Training model...
2022-10-26 11:28:56.647155: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 614400000 exceeds 10% of free system memory.
Epoch 1/60
Traceback (most recent call last):
  File "/home/evgenii/Documents/libs/beatmup/python/examples/cifar100.py", line 99, in <module>
    model.fit(train_images, train_labels, epochs=60, batch_size=256,
  File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/evgenii/miniconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  filter_size does not have enough elements, requested 124416, got 10368
         [[node gradient_tape/sequential/conv6/Conv2D/Conv2DBackpropFilter
 (defined at /home/evgenii/miniconda3/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py:464)
]] [Op:__inference_train_function_3183]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/sequential/conv6/Conv2D/Conv2DBackpropFilter:
In[0] sequential/shuffle_3/shuffle_3_shuffle (defined at /home/evgenii/miniconda3/lib/python3.9/site-packages/beatmup_keras.py:83)
In[1] gradient_tape/sequential/conv6/Conv2D/ShapeN:
In[2] gradient_tape/sequential/batch_normalization_5/FusedBatchNormGradV3:

Operation defined at: (most recent call last)
>>>   File "/home/evgenii/Documents/libs/beatmup/python/examples/cifar100.py", line 99, in <module>
>>>     model.fit(train_images, train_labels, epochs=60, batch_size=256,
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/engine/training.py", line 878, in train_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/engine/training.py", line 867, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/engine/training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/engine/training.py", line 816, in train_step
>>>     self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 530, in minimize
>>>     grads_and_vars = self._compute_gradients(
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 583, in _compute_gradients
>>>     grads_and_vars = self._get_gradients(tape, loss, var_list, grad_loss)
>>> 
>>>   File "/home/evgenii/miniconda3/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 464, in _get_gradients
>>>     grads = tape.gradient(loss, var_list, grad_loss)
>>>

**Comment by lnstadrum** [comment] 2022-10-26 17:16
Hello,

Thank you for your interest to Beatmup (again).

On my side the script is working, the model is training as expected (TF 2.7, RTX2070). Please provide more details on your setup (software and hardware).

lnstadrum

**Comment by jenamax** [comment] 2022-10-27 06:32
I have video card RTX 3080, TF version - 2.7, nvidia driver - 460 and cuda 11.2

**Comment by jenamax** [comment] 2022-10-27 09:30
Update: fixed by reinstalling cuda toolkit. Now I get and error during the conversion of model from tf to beatmup:

Traceback (most recent call last):
  File "/home/evgenii/Documents/libs/beatmup/python/examples/cifar100.py", line 118, in <module>
    test_model, test_model_data = beatmup_keras.export_model(model, ctx)
  File "/home/evgenii/miniconda3/lib/python3.9/site-packages/beatmup_keras.py", line 406, in export_model
    if input in inputs:
TypeError: argument of type 'KerasTensor' is not iterable

**Comment by lnstadrum** [comment] 2022-10-28 11:11
Hello,

The issue is reproducible on my side. Will investigate and provide a fix shortly.

lnstadrum

**Comment by lnstadrum** [comment] 2022-10-31 13:12
Hello,

A fix is provided in [issue/24 branch](https://github.com/lnstadrum/beatmup/tree/issue/24). The example model export and further inference work as expected for me. Would appreciate if you can check it out.

Thanks,
lnstadrum

**Comment by lnstadrum** [comment] 2022-12-11 18:15
The fix is merged to the main branch.

**Closed as completed by lnstadrum** 2022-12-11 18:15 UTC
