### ISSUE TITLE
Raspberry Pi 4 gpu failed to add service

### ISSUE THREAD

**Issue by MaxiDoet** [lnstadrum/beatmup#12] opened 2021-03-31 08:42 UTC
I compiled beatmup successfully but when i ran it, it returned an error:
![image](https://user-images.githubusercontent.com/38401902/113116187-7f208580-920d-11eb-98f2-8204fc700fb9.png)

I tried Legacy GL and Fake KMS (Full KMS isnt avaiable on Twister OS)

My Specs:
Model: Raspberry Pi 4 Model B
RAM: 8GB
OS: Twister OS 32bit

**Comment by lnstadrum** [comment] 2021-03-31 11:45
Hi @TheHeroCraft1579,

I do not have a Raspberry Pi 4 at hand to give it a try unfortunately.

The error message does not come from Beatmup though. As I could google out, it seems quite a common issue on Raspberry Pi somehow related to the OpenGL driver. You mention that you tried different driver options, so basic suggestions I might have would likely not help you much.

 * Could you try the two following build commands starting from a clean `build` folder every time?
   * `cmake -DUSE_EGL=ON ..` => usual build using EGL backend and proprietary Raspberry Pi drivers,
   * `cmake -DUSE_GLX=ON ..` => using GLX backend, usually works on desktop linux.
 * Could you post the output of these cmake commands? This is to check if it mentions that it finds the closed-source legacy driver.
 * To make sure, is the legacy drive present in `/opt/vc` folder?
 * A very old post [here](https://www.raspberrypi.org/forums/viewtopic.php?t=15209) suggests to increase the memory split. I believe it might be applicable on Pi 4 running the legacy driver. On Pi Zero W and Pi 3 B I have indeed `gpu_mem=128` in `config.txt`, because the shader programs contain the neural net weights and require relatively more memory. I would suggest you to try this as well.

I will try to find a Pi 4 but no promises here.

**Comment by MaxiDoet** [comment] 2021-03-31 12:38
cmake -DUSE_EGL=ON:

![image](https://user-images.githubusercontent.com/38401902/113144144-3c6ea580-922d-11eb-8ce4-9c61e3dffb3c.png)

cmake -DUSE_GLX=ON:

![image](https://user-images.githubusercontent.com/38401902/113144691-d1719e80-922d-11eb-88fa-4d535108ed1c.png)

![image](https://user-images.githubusercontent.com/38401902/113144968-26adb000-922e-11eb-8ae4-03814038d3ee.png)
I switched to a desktop but got the next error:

![image](https://user-images.githubusercontent.com/38401902/113145074-48a73280-922e-11eb-9aa1-91b981c888bb.png)

Looks like my pi has the /opt/vc folder and the memory split is set to 256MB

Maybe i need to switch to raspbian (because it has full-kms). Also VideoCoreVI isn't supported as much as VideoCoreIV.

**Comment by lnstadrum** [comment] 2021-03-31 21:04
Hi @TheHeroCraft1579,

Thanks for the update. The driver binaries are indeed where they are expected to be, and the memory split seems fine. I am searching for a Raspberry Pi 4 to investigate why the EGL backend does not work. Indeed, switching to Raspbian might help (all my tests are done in Raspbian on different models prior to Pi 4). I agree with the concern about VideoCore VI support; I'll see how much this is fixable once I get a Pi 4.

As for the GLX backend and the error you have got, I reproduced a similar thing on a desktop machine. Could you try out the branch `bugfix/glx_pbuffer_issue` in the same setup (`cmake -DUSE_GLX=ON ..`)? It will take me some time to get to a proper implementation mergeable to the main branch, but if it would be great to know if it gets any better there.

Just in case, even if it is irrelevant to the issue, you seem to be using Windows, and the neural upscaler should work fine there in Python. Just do `pip install beatmup` and run `python/examples/x2_superresolution.py` if ever you want to try it out, no need to compile.

**Comment by MaxiDoet** [comment] 2021-04-01 09:10
As you suggested i switched the branch to **bugfix/glx_pbuffer_issue**

### Twister OS:

First i forgot to clone the submodules but after doing that it worked:
![image](https://user-images.githubusercontent.com/38401902/113262399-da677c00-92d0-11eb-8efb-d453a5aa6a4a.png)

**To my suprise it worked (except some fragment shaders):**

![image](https://user-images.githubusercontent.com/38401902/113263034-9628ab80-92d1-11eb-99d2-b60cf0dfebb4.png)
![image](https://user-images.githubusercontent.com/38401902/113263221-cc662b00-92d1-11eb-979b-d765db4e59b7.png)

### Raspbian OS:

On raspbian it couldn't find opengl
![image](https://user-images.githubusercontent.com/38401902/113267619-db9ba780-92d6-11eb-8790-d9ed87a0823a.png)

sudo apt-get install libgles2-mesa libgles2-mesa-dev

![image](https://user-images.githubusercontent.com/38401902/113269490-ca539a80-92d8-11eb-9839-68280db41162.png)

sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

![image](https://user-images.githubusercontent.com/38401902/113269764-143c8080-92d9-11eb-80d6-5142b2e8c9a8.png)

So i guess something went wrong with the opengl driver on the raspberry because full-kms isn't event avaiable in raspbian

So the last thing i tried was to use the original cmake args for the raspberry: DUSE_EGL=ON
But i still got segmentation fault which i think i caused by installing mesa.

Maybe this is interesting to you too:
![image](https://user-images.githubusercontent.com/38401902/113271043-66ca6c80-92da-11eb-89de-e244f9e0f29b.png)

Maybe you download twister os when you have a raspberry pi 4 and look for these drivers because i dont know much about opengl.

**Comment by lnstadrum** [comment] 2021-04-04 20:06
Hi @TheHeroCraft1579 ,

Thanks for the update.

I got a Pi 4 and reproduced the original "failed to add service" issue in the latest Raspbian. The fix is provided in `bugfix/pi4` branch.

In short, there were two problems.

 * On Pi 4, neither the legacy closed-source EGL nor standard mesa EGL implementation appear to be unusable on Pi 4. I implemented an EGL backend variant using libdrm/libgbm on top of Mesa EGL as Internet suggest [here](https://www.raspberrypi.org/forums/viewtopic.php?t=273270#p1656993), [here](https://github.com/matusnovak/rpi-opengl-without-x), [here](https://www.raspberrypi.org/forums/viewtopic.php?t=274895#p1669918).

 * The best part of Beatmup was working with the GLX backend in the branch I suggested you to try lastly, but X2 was not. It turned out that VideoCore 6 puts a stronger constraint on number of registers per thread. Stronger than Pi 3B+, Pi Zero W, few mobile GPUs tested in Android and desktop GPUs... so some shaders failed to execute. I refactored 3x3 grouped convolutions shaders to reduce the register pressure and get X2 working with VC6.

So in `bugfix/pi4` branch X2 works on Pi 4 producing correctly upscaled sharp images (checked visually taking the master branch implementation as a reference).

The fix introduces some changes in Beatmup fundamentals that are not Pi 4-specific, so I will be testing it on other hardware, but it is very likely a master candidate.

I did not have time to test with Twister OS. Chances are that the problem was the same there. I will appreciate a lot if you can try it out.

I put a detailed instruction in the next comment that I plan to refer in the repository readme for others.

lnstadrum

**Comment by lnstadrum** [comment] 2021-04-04 20:12
Here goes a detailed description of how to get things working on **Raspberry Pi 4**.

Hardware tested: Raspberry Pi 4 rev 1.2, 4 GB RAM
Software tested: Raspberry Pi OS with desktop,
 *  Release date: March 4th 2021
 *  SHA256 checksum: `d3de1a33d2d4f4990345b6369960b04c70b577519e6f25f4d7ec601e305e932a`

The following four steps are exclusively **for Raspberry Pi 4, not for older models**.

### (1) Flashing an SD card with the OS

Nothing special.

### (2) Headless setup
This is likely optional if you have a screen and a keyboard to connect to the board.
  * Enable ssh and a network connection (Wi-Fi in my test) as explained in countless headless setup tutorials.
  * Put the SD card in the board, power on, connect by SSH
  * To test the GLX backend, an X server connection is needed. In this test I used VNC. To get it working,
     * `sudo raspi-config`
     * Enable VNC in `Interface Options` > `VNC`
     * A virtual display needs to be set up by choosing a non-default resolution in `Display Options` > `Resolution`. I put DMT mode 16, any non-default choice likely works as well.
     * Hit "Finish", reboot

### (3) Using Beatmup with GLX backend

Get a working X connection from your PC to Raspberry Pi.
 * VNC worked in this test.
 * `ssh -X` might presumably do the job if properly configured, but not just a simple ssh connection.
 * Should also work with a physical screen and keyboard connected to Pi (I could not test this).

Get the code:

    git clone https://github.com/lnstadrum/beatmup.git
    cd beatmup/

Get submodules:
    
    git submodule update --init --recursive

Install the software: CMake and GLX-related libs

    sudo apt install libgl1-mesa-dev libglu1-mesa-dev libglx-dev cmake
   
Build X2 app with GLX:

    mkdir build && cd build
    cmake -DUSE_GLX=ON ..
    make -j4 X2

Test the app on an image

    ./X2 ../images/fecamp.bmp test.bmp

The output I got:

    Preparing GPU... 
    Broadcom | V3D 4.2
    Compiling shaders... 9707.59 ms
    Transfering input to GPU... 
    Processing... 
      1797.55 ms
    Saving result to test.bmp

The upscaled image is in `test.bmp`. Looks nice.

All the other apps can be built similarly.

### (4) Using EGL backend

Beatmup also works with EGL. This option is usable both headless through a simple SSH connection without X and with graphic interface. A virtual display is still required to be set up (see step 2).

Install the software: CMake and EGL libs

    sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libdrm-dev libgbm-dev

Build X2 app with EGL backend (run in `build` folder):

    cmake -DUSE_GLX=OFF -DUSE_EGL_DRM=ON -DGLES_VERSION=20 ..
    make -j4 X2
    ./X2 ../images/fecamp.bmp test.bmp

CMake is supplied with `GLX=OFF` option: the build is done in the same build folder after the GLX test above.

Test the app on an image. Same as above.

In case of error "Cannot get DRM resources", setting the DRI device from `card1` to `card0` before running any app may help:

    export BEATMUP_DRI_DEVICE=/dev/dri/card0

### Other Pi models prior to 4

On other models prior to Raspberry Pi 4 only EGL backend is supported. With the rest remaining the same, the corresponding cmake build command to run from a clean build folder is:

    cmake -DUSE_EGL=ON -DUSE_BRCM_LIBS=ON -DGLES_VERSION=20 ..

**Comment by MaxiDoet** [comment] 2021-04-05 09:17
Any updates yet?

**Comment by lnstadrum** [comment] 2021-04-05 09:33
Hi @TheHeroCraft1579,

See two my comments from yesterday just above. Did that work for you?

lnstadrum

**Comment by MaxiDoet** [comment] 2021-04-05 11:03
Sorry for asking, github didn't show me your update.

I tried the GLX Method but got a **segmentation fault** (on a fresh installation):
![image](https://user-images.githubusercontent.com/38401902/113567608-36067200-960f-11eb-8305-74b5529a7eaf.png)


The EGL Method worked fine:
![image](https://user-images.githubusercontent.com/38401902/113567526-12432c00-960f-11eb-9198-dc57db4faa76.png)

**Comment by lnstadrum** [comment] 2021-04-05 11:18
Thanks for trying!

Sorry, I have to bother you more to understand what exactly is happening.

* Is it Twister OS or Raspbian?

* What bothers me in the EGL test is this "VMWare" mention instead of the actual GPU model. Could you please post the output of the following command after the EGL compilation?
    `cat CMakeCache.txt | grep USE_`

* In the GLX test do you have a physical screen connection or you run this from a remote machine? If latter, do you have an X server connection?

* For the GLX test could you please try to compile and run X2 with the following command from a clean build folder?
    `cmake -DUSE_GLX=ON -DDEBUG=ON ..`

lnstadrum

**Comment by MaxiDoet** [comment] 2021-04-05 12:31
- It is raspbian os 32bit
- ![image](https://user-images.githubusercontent.com/38401902/113573581-ba122700-961a-11eb-8876-dbe5d3967e1d.png)
- I connected via vnc (`vncserver-virtual`)
- After compiling with `cmake -DUSE_GLX=ON -DDEBUG=ON ..`
cmake output:
![image](https://user-images.githubusercontent.com/38401902/113574049-9ef3e700-961b-11eb-99bd-03f187fb1a23.png)

![image](https://user-images.githubusercontent.com/38401902/113573970-7966dd80-961b-11eb-8e38-e445f7b5c45d.png)

**Comment by lnstadrum** [comment] 2021-04-05 12:57
Thanks for the update.

As far as I see from your reply, everything is okay.

Trying to reproduce the issue I switched to the legacy OpenGL driver and got the mention of VMWare appearing and comparable runtime to what you posted. Still no segfault though neither with GLX, nor with EGL (the behaviour is basically same for me). The produced image in this case is looking correctly. However, the processing time is sensibly slower (2.2 s vs 1.8 s as I posted above), and the shaders compilation is just slow as hell in this case.

Is there any chance that the Raspbian distribution you got is an old one?

lnstadrum

**Comment by MaxiDoet** [comment] 2021-04-05 12:58
I flashed it 1 hour ago using the rpi-imager tool

**Comment by lnstadrum** [comment] 2021-04-05 13:47
I installed rpi-imager, flashed the SD card with "Raspberry Pi OS (32 bit)", enabled SSH and Wi-Fi, set up VNC and display in raspi-config over SSH and so on as described in my comment above. GLX goes as expected:

    Preparing GPU... 
    Broadcom | V3D 4.2
    Compiling shaders... 9646.44 ms
    Transfering input to GPU... 
    Processing... 
      1601.03 ms
    Saving result to x2.bmp

No clue on what is happening on your side. Likely the last suggestion would be to make sure that the GL driver is not set to legacy.

lnstadrum

**Comment by lnstadrum** [comment] 2021-04-05 14:04
Ah, btw, the first time I saw this VMware / llvm string was when I tried GLX/EGL test on Pi 3B+, not 4. Stupid question then: did not you accidentally change your Pi 4 board by another model?

lnstadrum

**Comment by MaxiDoet** [comment] 2021-04-05 14:05
No i didn't :-)

**Comment by MaxiDoet** [comment] 2021-04-05 14:10
I heard that now you can select if ssh should be enabled by default but rpi-imager didn't ask me to so maybe i need to update it

**Comment by MaxiDoet** [comment] 2021-04-20 06:19
I tried it again today but i got this error:
![image](https://user-images.githubusercontent.com/38401902/115346880-07f96400-a1b1-11eb-9651-710a1f07f727.png)

OS: Raspbian OS Lite 32bit (not new)
Raspberry Pi 4b 8GB

Edit: I tried both cmds:
cmake -DUSE_EGL=ON -DUSE_BRCM_LIBS=ON -DGLES_VERSION=20 ..
cmake -DUSE_EGL_DRM=ON -DGLES_VERSION=20 ..

**Comment by lnstadrum** [comment] 2021-04-20 07:02
Hi @TheHeroCraft1579,

This is likely because of missing submodules. Did you do `git submodule update --init --recursive`?

lnstadrum

**Comment by MaxiDoet** [comment] 2021-04-20 08:28
Sorry for that xD
![image](https://user-images.githubusercontent.com/38401902/115363833-1781a880-a1c3-11eb-907c-88119f5dce64.png)

Im gonna try it on a fresh installation today and then give you an update

**Comment by lnstadrum** [comment] 2021-04-20 18:01
Oh, I see.

"USE_EGL" option should not work on Pi 4 and leads to this "already in use" error indeed.
"USE_EGL_DRM" should work. But bear in mind the fact that CMake has a cache, and if you just rerun CMake in the same build folder twice with different options, `USE_BRCM_LIBS` remains set to `ON` since the first run, at least you do not pass explicitly `-DUSE_BRCM_LIBS=OFF`.

This is why it is safer to `rm -rf build` every time you change CMake options.

On the other note, 2.1 release has been rolled out. It implements the Pi 4 support, but there is no much difference with the test branch I provided previously. It was quite thoroughly tested though. It would be great to conclude on this issue, so if you can try a recent Raspberry Pi OS release, that would be great.

**Comment by arkadijs** [comment] 2021-09-16 20:41
Latest source from master works fine on up to date Pi 4 - both in GLX and EGL_DRM mode. Mesa 21.1.7 installed into /usr/local.

**Comment by lnstadrum** [comment] 2021-09-19 09:30
Thanks @arkadijs for checking this out! Closing this issue then.

**Closed as completed by lnstadrum** 2021-09-19 09:30 UTC
